### ISSUE TITLE
Form "require" validation

### ISSUE THREAD

**Issue by 4rokis** [cheatcode/joystick#266]
These form validation rules should behave the same.
```
const booleanValue = false
 'expire-at': {
    ...(booleanValue ? { required: true } : {}))
  },
```
and 
```
const booleanValue = false
 'expire-at': {
    required: booleanValue
  },
```

**Expected:** 
Based on the "booleanValue" the tested field gonna be required.

**Actual**
Regardless of the "booleanValue", if the required is set it will validate as "required"

**Comment by rglover** [comment]
Can you clarify a bit...are you saying that `required` always validates to `true`, or something else?
