### ISSUE TITLE
The command 'joystick create <app name>' not working after installed

### ISSUE THREAD

**Issue by artemshar** [cheatcode/joystick#378]
I followed directly to the instruction of installation: https://github.com/cheatcode/joystick?tab=readme-ov-file#installation

**Environment**:
Windows, bash terminal in VSCode.
I tested in Node.js v.18.18.0 and 22.2.0

**Issue**:

1. ```npm i @joystick.js/cli@latest``` installing all dependencies locally, everything is ok.
2. ```joystick create <app_name>``` I received the error: ```bash: joystick: command not found```

So, only this command worked for me ```node ./node_modules/@joystick.js/cli/dist/cli.js create <app_name>``` and the app was initialized. But that's certainly not how it's supposed to work.

**Solution**:
I tried to install globally ```npm i @joystick.js/cli@latest -g```, so then the CLI command ```joystick create <app_name>``` was worked.

**Proposal**:
You can simply fix the documentation if you want to tell users - install the CLI globally. Or make the CLI visible when installing locally (I don't know, I've never developed a CLI).

**Comment by rglover** [comment]
Hey @artemshar, appreciate the heads up on this missing. Corrected. I'm going to close this as it sounds like you resolved the issue but feel free to reopen if you're still having issues.
